server:
  port: 18072
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1



spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/traffic_science?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: liangkeyiwei
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:D:/jtjsfwcenter/file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/traffic_science?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#    username: root
#    password: liangkeyiwei
#    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapperLocations: classpath:cn.com.busi.mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    path: d:/jtjsfwcenter/logs




